HOST_NAME = "HostName"
IP = "IP"
SCORE = "Score"
PING = "Ping"
SPEED = "Speed"
COUNTRY_LONG = "CountryLong"
COUNTRY_SHORT = "CountryShort"
NUM_VPN_SESSIONS = "NumVpnSessions"
UPTIME = "Uptime"
TOTAL_USERS = "TotalUsers"
TOTAL_TRAFFIC = "TotalTraffic"
LOG_TYPE = "LogType"
OPERATOR = "Operator"
MESSAGE = "Message"
OPENVPN_CONFIG_DATA = "OpenVPN_ConfigData"
PROTOCOL = "Protocol"

CSV_HEADER = [
    HOST_NAME, IP, SCORE, PING, SPEED,
    COUNTRY_LONG, COUNTRY_SHORT, NUM_VPN_SESSIONS,
    UPTIME, TOTAL_USERS, TOTAL_TRAFFIC, LOG_TYPE, OPERATOR,
    MESSAGE, OPENVPN_CONFIG_DATA
]